version: 2
jobs:
   build:
     docker:
       - image: clojure:tools-deps-alpine

     # It’s a little tricky to get working_directory and checkout to work
     # together when I want the working directory for all steps *except*
     # checkout to be a subdirectory of the project — because by default,
     # checkout checks out into the specified working_directory. I found this
     # solution here: https://stackoverflow.com/a/50570581/7012
     working_directory: ~/project/tool

     steps:
       - checkout:
           path: ~/project

       - restore_cache:
           keys:
           - dependencies-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - dependencies-

       - run:
          name: Download dependencies (if necessary)
          # Clojure automatically downloads deps if necessary
          command: "clojure -R:test:test/coverage:lint -Sdescribe"

       - save_cache:
           key: dependencies-{{ checksum "deps.edn" }}
           paths:
           - .cpcache
           - ~/.m2
           - ~/.gitlibs

       - run:
          name: Run tests and measure test coverage
          # The max heap size is set to 2GB because I’ve seen OOM errors at 1GB and below. (JDK 8
          # defaults to setting the max heap to ¼ of the total RAM, and CI containers frequently have
          # <= 4GB RAM.)
          command: "clojure -J-Xmx2g -A:test:test/coverage"

       - store_test_results:
          path: target/test-results

       - store_artifacts:
          path: target/coverage

       - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

       - run:
          name: lint
          command: "clojure -A:lint"
