version: 2
jobs:
   build:
     docker:
       - image: clojure:tools-deps-alpine
     steps:
       - checkout

       - restore_cache:
           keys:
           - dependencies-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - dependencies-

       - run:
          name: Download dependencies (if necessary)
          # Clojure automatically downloads deps if necessary
          command: "clojure -R:test:test/run:coverage:lint -e '(println \"deps are installed!\")'"

       - save_cache:
           key: dependencies-{{ checksum "deps.edn" }}
           paths:
           - ~/.m2
           - ~/.gitlibs

       - run:
          name: Run tests and measure test coverage
          # The max heap size is set to 2GB because I’ve seen OOM errors at 1GB and below. (JDK 8
          # defaults to setting the max heap to ¼ of the total RAM, and CI containers frequently have
          # <= 4GB RAM.)
          command: "clojure -J-Xmx2g -A:test:coverage"

       - store_test_results:
          path: target/test-results

       - store_artifacts:
          path: target/coverage

       - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

       - run:
          name: lint
          command: "clojure -A:lint"
