version: 2

# All the tool_* jobs specify the checkout path, and then set a
# `working_directory` that’s different than the default and is _underneath_ the
# checkout path. This is because it’s a little tricky to get `working_directory`
# and `checkout` to work together when I want the working directory for all
# steps *except* `checkout` to be a subdirectory of the project — because by
# default, `checkout` checks out into the specified `working_directory`. I found
# this solution here: https://stackoverflow.com/a/50570581/7012
tool_job_defaults: &tool_job_defaults
  working_directory: ~/project/tool
  docker:
    - image: quay.io/fundingcircle/clojure-node-chromium:clojure-1.9.0.394_node-10.12_alpine-3.8

restore_cache_clj: &restore_cache_clj
  name: Restore cached Clojure dependencies
  keys:
  - clj-deps-{{ checksum "deps.edn" }}
  # fallback to using the latest cache if no exact match is found
  - clj-deps-

restore_cache_node: &restore_cache_node
  name: Restore cached Node dependencies
  keys:
  - node-deps-{{ checksum "renderer/package.json" }}
  # fallback to using the latest cache if no exact match is found
  - node-deps-

jobs:
   tool_deps:
     <<: *tool_job_defaults
     steps:
       - checkout:
           path: ~/project
       - restore_cache:
           <<: *restore_cache_clj
       - restore_cache:
           <<: *restore_cache_node

       - run:
          name: Download Clojure Dependencies (if necessary)
          command: bin/download-clojure-deps

       - run:
          name: Download Node Dependencies (if necessary)
          command: bin/download-node-deps

       - save_cache:
           name: Save Clojure Dependencies (if changed)
           key: clj-deps-{{ checksum "deps.edn" }}
           paths:
           - .cpcache
           - ~/.m2
           - ~/.gitlibs

       - save_cache:
           name: Save Node Dependencies (if changed)
           key: node-deps-{{checksum "renderer/package.json"}}
           paths:
           - renderer/node_modules

   tool_test:
     <<: *tool_job_defaults
     steps:
       - checkout:
           path: ~/project
       - restore_cache:
           <<: *restore_cache_clj
       - restore_cache:
           <<: *restore_cache_node

       - run:
          name: Run tests and measure test coverage
          command: bin/tests-with-coverage

       - store_test_results:
          path: target/test-results

       - store_artifacts:
          path: target/coverage

       - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

   tool_lint:
     <<: *tool_job_defaults
     steps:
       - checkout:
           path: ~/project
       - restore_cache:
           <<: *restore_cache_clj
       - restore_cache:
           <<: *restore_cache_node
       - run:
          name: lint
          command: clojure -A:lint

   tool_build_dist_pkg:
     <<: *tool_job_defaults
     steps:
       - checkout:
           path: ~/project
       - restore_cache:
           <<: *restore_cache_clj
       - restore_cache:
           <<: *restore_cache_node
       - restore_cache:
           name: Restore cached Clojure dependencies needed for building uberjar
           keys:
           - clj-uberjar-deps-{{ checksum "deps.edn" }}-{{checksum "bin/download-pkg-deps"}}
           - clj-uberjar-deps-
       - restore_cache:
           name: Restore cached Node dependencies needed for packaging renderer
           keys:
           - node-package-deps-{{ checksum "renderer/package.json" }}-{{checksum "bin/download-pkg-deps"}}
           - node-package-deps-
       - run:
           name: Download dependencies needed for building dist package
           command: bin/download-pkg-deps
           environment:
             # Workaround for https://github.com/nodejs/docker-node/issues/813
             npm_config_unsafe_perm: true
       - run:
           name: Create distribution packages
           command: |
             bin/pkg-all
             mkdir -p /workspace/packages
             mv target/pkg/*.gz /workspace/packages/
       - persist_to_workspace:
           root: /workspace
           paths: [packages]
       - store_artifacts:
           # Not entirely sure we need these artifacts but seems like a good idea just in case.
           path: /workspace/packages
       - save_cache:
           name: Cache the Clojure dependencies needed for building uberjar
           key: clj-uberjar-deps-{{ checksum "deps.edn" }}-{{checksum "bin/download-pkg-deps"}}
           paths:
           # I *guess* this will end up overwriting the deps restored via
           # restore_cache_clj but I’m hoping that’s OK.
           - .cpcache
           - ~/.m2
           - ~/.gitlibs
       - save_cache:
           name: Cache the Node Dependencies needed for packaging renderer
           key: node-package-deps-{{checksum "renderer/package.json"}}-{{checksum "bin/download-pkg-deps"}}
           # ~/.npm is needed here because that is (or includes) npm’s cache, and that’s where pkg
           # downloads the built node runtimes for various platforms.
           paths: [~/.npm, ~/node_modules]

   tool_publish_dist_pkg:
     <<: *tool_job_defaults
     steps:
       - attach_workspace:
            at: /workspace
       - run:
           name: Check crucial environment variables
           command: |
             [ "$GITHUB_TOKEN" ] || { echo 'GITHUB_TOKEN is not set!' && exit 1; }
       - run:
           ## TODO: cache ghr
           name: Download and unpack ghr
           command: |
             wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
             tar -xzf ghr_v0.12.0_linux_amd64.tar.gz --strip-components 1 ghr_v0.12.0_linux_amd64/ghr
       - run:
           name: Create GitHub Release and upload distribution packages to it
           # Docs for ghr’s options: https://github.com/tcnksm/ghr/#options
           command: |
             TAG="${CIRCLE_BRANCH}_$(date "+%Y-%m-%d")_${CIRCLE_BUILD_NUM}"
             ./ghr -t $GITHUB_TOKEN \
                   -u $CIRCLE_PROJECT_USERNAME \
                   -r $CIRCLE_PROJECT_REPONAME \
                   -c $CIRCLE_SHA1 \
                   $TAG \
                   /workspace/packages

workflows:
  version: 2
  tool:
    jobs:
      - tool_deps
      - tool_test: {requires: [tool_deps]}
      - tool_lint: {requires: [tool_deps]}
      - tool_build_dist_pkg: {requires: [tool_test, tool_lint]}
      - tool_publish_dist_pkg:
          requires: [tool_build_dist_pkg]
          filters: {branches: {only: master}}
