version: 2
jobs:
   build:
     docker:
       - image: circleci/clojure:tools-deps
     steps:
       - checkout

       # Restore the dependencies cache, if it exists
       - restore_cache:
           keys:
           - dependencies-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - dependencies-

       # Download deps if necessary. (clojure automatically downloads deps if necessary)
       - run: "clojure -R:run-tests -e '(println \"deps are installed!\")'"

       # Run the tests
       # The max heap size is set to 2GB because I’ve seen OOM errors at 1GB and below. (JDK 8
       # defaults to setting the max heap to ¼ of the total RAM, and CI containers frequently have
       # <= 4GB RAM.)
       - run: "clojure -J-Xmx2g -A:run-tests"

       # Save the dependencies cache
       - save_cache:
           key: dependencies-{{ checksum "deps.edn" }}
           paths:
           - ~/.m2
           - ~/.gitlibs
