version: 2

# In many of the jobs below, you’ll see `working_directory` specified, and that
# the `checkout` step has a different path specified (the default path). This is
# because it’s a little tricky to get `working_directory` and `checkout` to work
# together when I want the working directory for all steps *except*
# `checkout` to be a subdirectory of the project — because by default,
# `checkout` checks out into the specified `working_directory`. I found this
# solution here: https://stackoverflow.com/a/50570581/7012

jobs:
   tool_deps:
     docker:
       - image: quay.io/fundingcircle/clojure-node-chromium:clojure-1.9.0.394_node-10.12_alpine-3.8

     working_directory: ~/project/tool

     steps:
       - checkout:
           path: ~/project

       - restore_cache:
           name: Restore Clojure Dependencies (if cached)
           keys:
           - clj-deps-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - clj-deps-

       - restore_cache:
           name: Restore Node Dependencies (if cached)
           keys:
           - node-deps-{{checksum "renderer/package.json"}}
           # fallback to using the latest cache if no exact match is found
           - node-deps-

       - run:
          name: Download Clojure Dependencies (if necessary)
          command: bin/download-clojure-deps

       - run:
          name: Download Node Dependencies (if necessary)
          command: bin/download-node-deps

       - save_cache:
           name: Save Clojure Dependencies (if changed)
           key: clj-deps-{{ checksum "deps.edn" }}
           paths:
           - .cpcache
           - ~/.m2
           - ~/.gitlibs

       - save_cache:
           name: Save Node Dependencies (if changed)
           key: node-deps-{{checksum "renderer/package.json"}}
           paths:
           - renderer/node_modules

   tool_test:
     docker:
       - image: quay.io/fundingcircle/clojure-node-chromium:clojure-1.9.0.394_node-10.12_alpine-3.8

     working_directory: ~/project/tool

     steps:
       - checkout:
           path: ~/project

       - restore_cache:
           name: Restore Clojure Dependencies
           keys:
           - clj-deps-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - clj-deps-

       - restore_cache:
           name: Restore Node Dependencies
           keys:
           - node-deps-{{checksum "renderer/package.json"}}
           # fallback to using the latest cache if no exact match is found
           - node-deps-

       - run:
          name: Run tests and measure test coverage
          command: bin/tests-with-coverage

       - store_test_results:
          path: target/test-results

       - store_artifacts:
          path: target/coverage

       - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

   tool_lint:
     docker:
       - image: quay.io/fundingcircle/clojure-node-chromium:clojure-1.9.0.394_node-10.12_alpine-3.8

     working_directory: ~/project/tool

     steps:
       - checkout:
           path: ~/project

       - restore_cache:
           keys:
           - clj-deps-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - clj-deps-

       - run:
          name: lint
          command: clojure -A:lint

workflows:
  version: 2
  tool:
    jobs:
      - tool_deps
      - tool_test:
          requires:
            - tool_deps
      - tool_lint:
          requires:
            - tool_deps
