version: 2
jobs:
   build:
     docker:
       - image: circleci/clojure:tools-deps
     steps:
       - checkout

       # Restore the dependencies cache, if it exists
       - restore_cache:
           keys:
           - dependencies-{{ checksum "deps.edn" }}
           # fallback to using the latest cache if no exact match is found
           - dependencies-

       # Download deps if necessary. (clj automatically downloads deps if necessary)
       - run: "clojure -R:run-tests -e '(println \"deps are installed!\")'"

       # Run the tests
       # The max heap size is set to 1GB because CI machines/containers frequently have <=4GB of
       # RAM, and JDK 8 defaults to setting the max heap to 1/4 of the total RAM, but such a small
       # heap max leads to OOM errors when running the tests (at 512MB; I’ve only tested 512MB and
       # 1GB).
       - run: "clojure -J-Xmx1g -A:run-tests"

       # Save the dependencies cache
       - save_cache:
           key: dependencies-{{ checksum "deps.edn" }}
           paths:
           - ~/.m2
           - ~/.gitlibs
