title: FC4
description: A tool for cataloguing, modeling, and documenting software systems

defaults:
  - scope:
      path: methodology
      type: pages
    values:
      layout: default
  - scope:
      path: tool
      type: pages
    values:
      layout: default
  - scope:
      path: posts.md
      type: pages
    values:
      layout: default

theme: minima

## Stuff specific to Minima

header_pages:
  # - methodology/index.md
  # - tool/index.md
  - docs/tutorial/index.md
  - docs/index.md
  - news.md

## Stuff specific to GitHub Pages

repository: FundingCircle/fc4-framework
